# Generated by Django 5.0.6 on 2024-05-18 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_is_especialista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_especialista',
        ),
    ]
