# Generated by Django 5.0.6 on 2024-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_usuario_is_especialista"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="especialista",
            options={
                "verbose_name": "Especialista",
                "verbose_name_plural": "Especialistas",
            },
        ),
        migrations.AlterModelOptions(
            name="paciente",
            options={"verbose_name": "Paciente", "verbose_name_plural": "Pacientes"},
        ),
        migrations.AlterField(
            model_name="usuario",
            name="Cep_Usuario",
            field=models.CharField(max_length=8, verbose_name="CEP"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="Cpf_Usuario",
            field=models.CharField(max_length=11, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="Data_nsc_Usuario",
            field=models.DateField(
                max_length=999, null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="Endr_Usuario",
            field=models.CharField(max_length=100, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="Img_Usuario",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/img/",
                verbose_name="Imagem de Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="Sexo_Usuario",
            field=models.CharField(
                choices=[("F", "Feminino"), ("M", "Masculino")],
                max_length=10,
                verbose_name="Sexo do Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="Tel_Usuario",
            field=models.CharField(max_length=14, verbose_name="Telefone"),
        ),
    ]
