# Generated by Django 5.0.6 on 2024-05-20 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_especialista_options_alter_paciente_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="especialidade",
            options={
                "verbose_name": "Especialidade",
                "verbose_name_plural": "Especialidades",
            },
        ),
        migrations.AlterModelOptions(
            name="especialista",
            options={"verbose_name": "Médico", "verbose_name_plural": "Médicos"},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "Status", "verbose_name_plural": "Status"},
        ),
        migrations.AddField(
            model_name="especialidade",
            name="descricao",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="Descricao"
            ),
        ),
        migrations.AlterField(
            model_name="especialidade",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Dermatologista", "Dermatologista"),
                    ("Cirurgia", "Cirurgia"),
                    ("Clínica Geral", "Clínica Geral"),
                    ("Odontologia", "Odontologia"),
                ],
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="Especialidade",
            ),
        ),
        migrations.AlterField(
            model_name="especialista",
            name="especialidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.especialidade",
                verbose_name="Especialidade",
            ),
        ),
    ]
