# Generated by Django 5.0.6 on 2024-05-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_especialidade_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consulta",
            name="Id_Status",
        ),
        migrations.AddField(
            model_name="consulta",
            name="Status",
            field=models.CharField(default="A", max_length=1),
        ),
        migrations.DeleteModel(
            name="Status",
        ),
    ]
