# Generated by Django 5.0.6 on 2024-05-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_consulta_id_status_consulta_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='Id_Escpecialista',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='Id_Especialidade',
        ),
        migrations.AddField(
            model_name='consulta',
            name='Especialidade',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='Medico',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
