# Generated by Django 5.0.6 on 2024-05-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_consulta_id_escpecialista_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="is_especialista",
            field=models.BooleanField(default=False),
        ),
    ]
