# Generated by Django 5.0.6 on 2024-05-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_usuario_is_especialista"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ocupacao",
        ),
    ]
