# Generated by Django 5.0.6 on 2024-05-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_delete_ocupacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="is_especialista",
        ),
        migrations.AddField(
            model_name="especialista",
            name="is_especialista",
            field=models.BooleanField(default=True),
        ),
    ]
