# Generated by Django 5.0.6 on 2024-05-28 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_usuario_is_especialista_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consulta",
            name="Laudo",
        ),
        migrations.AddField(
            model_name="consulta",
            name="Prontuario",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="Especialidade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.especialidade",
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="Exame",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="Medico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.especialista",
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="Receita",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="Status",
            field=models.CharField(
                choices=[
                    ("A", "Agendada"),
                    ("C", "Cancelada"),
                    ("E", "Espera"),
                    ("R", "Realizada"),
                ],
                default="A",
                max_length=1,
            ),
        ),
    ]
