# Generated by Django 5.0.6 on 2024-05-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_consulta_laudo_consulta_prontuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="Especialidade",
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="Medico",
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
