# Generated by Django 5.0.6 on 2024-06-07 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_consulta_id_paciente_consulta_id_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="Id_Medico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_medico",
                to="core.especialista",
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="Id_Usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="id_usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
